settings:
  application:
    # dev开发环境 test测试环境 prod线上环境
    mode: dev
    # 服务器ip，默认使用 0.0.0.0
    host: 0.0.0.0
    # 服务名称
    name: myapp
    # 端口号
    port: 8080 # 服务端口号
  database:
    # 数据库类型 mysql，sqlite3， postgres
    driver: mysql
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    source: root:FuLe2012SS@tcp(127.0.0.1:3306)/im?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms
