definitions:
  app.Response:
    properties:
      code:
        description: 响应代码
        example: 200
        type: integer
      data:
        description: 数据集
        type: object
      msg:
        description: 响应消息
        type: string
    type: object
info:
  contact: {}
  description: MyApp 系统
  license:
    name: MIT
    url: https://www.xuxueyun.com
  title: galaxy-mail
  version: 1.0.0
paths:
  /api/v1/plans/{id}:
    get:
      description: 获取JSON
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: '{"code": 200, "data": [...]}'
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - "": []
      summary: 获取套餐数据
      tags:
      - 套餐
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
